apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: kube-system
  labels:
    app: nginx
spec:
  replicas: 1

  selector:
    matchLabels:
      lbtype: external

  template:
    metadata:
      labels:
        lbtype: external
        app: nginx
    spec:
      serviceAccountName: test-sa
      containers:
      - name: nginx
        image: nginx:latest
        tty: true
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: "1Gi"
        ports:
        - containerPort: 80
  
          name: nginx-port
